### PR TITLE
Scrapper, Taisia Solareva - 21FPL2

### PR DESCRIPTION
**Pull request by taisiyasolareva**

### CODE REVIEW

**Review by demid5111 — CHANGES_REQUESTED** [review]
nothing to review. hurry up!

**Review by demid5111 — CHANGES_REQUESTED** [review]
no progress, your work is at risk for the deadline

**Review by demid5111 — CHANGES_REQUESTED** [review]
no progress, your work is at high risk for the deadline

**Comment by demid5111** [comment]
ALERT: transfer of mentor. Now your mentor is @dmitry-uraev

**Review by dmitry-uraev — CHANGES_REQUESTED** [review]
no progress

**Comment by dmitry-uraev** [comment]
it is right time to finish your implementation

**Comment by dmitry-uraev** [comment]
No progress since last review

**Comment by dmitry-uraev** [comment]
No progress since last review

**Comment by dmitry-uraev** [comment]
No progress since last review

**Comment by dmitry-uraev** [comment]
There is not so much time left. Keep up. 

I think you need a higher lab score than 4.

**Comment by dmitry-uraev** [comment]
It is time to implement pipeline as well

**Comment by dmitry-uraev** [comment]
you may do it in current PR

**Pull request closed without merging**
