### PR TITLE
Pipeline, Maxim Matveev - 21FPL1

### PR DESCRIPTION
**Pull request by yourMasya**
hwga

### CODE REVIEW

**Review by marina-kaz — COMMENTED** [review]
No progress in pipeline, that would mean that I have to increase the penalty up to -3. 

Also, discard all the changes in the files other than `requirements.txt` and in `lab_5_scrapper` and `lab_6_pipeline` folders

**Comment by yourMasya** [comment]
What if I made some progress in recursive crawler for lab 5? Alexander Vladimirovich asserted that it's possible to create 1 pull request for both labs, so I centered around scrapper and attempted to higher my grade in the previous lab at first.

**Review by marina-kaz — COMMENTED** [review]
No significant changes since my last review

**Comment by marina-kaz** [comment]
As for the penalty, indeed, it was canceled soon after. 
The original rule was to penalize those who have not started working on the pipeline by Monday, but the new rule asserts that having a dedicated MR with no substantial pipeline progress is also enough.

**Pull request closed without merging**
